quiz_app/quizes/__init__.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session

from quiz_app.mysql_cursor import MySqlCursor
from quiz_app.forms import *

from ..quiz_register import *
from ..admin_register import *
from ..answer_register import *
from ..user_register import *
from ..user_has_quiz import *
from ..user_has_answer import *
from ..mysql_cursor import *
from ..db import *
from ..utils import *

import random

quizes = Blueprint('quizes', __name__, url_prefix='/quizes')


@quizes.route('/index')
@quizes.route('/home')
@quizes.route('/')
def home():
    user = db_query_single("SELECT * FROM user WHERE id=%s", [session.get('id')])
    quizes = db_query_rows("SELECT * FROM quiz")

    current_user_has_quiz = db_query_rows("SELECT * FROM user_has_quiz INNER JOIN user ON user_id=user.id WHERE user_id=%s", [session.get('id')])
    current_user_quizes = {}
    if current_user_has_quiz:
        for list in current_user_has_quiz:
            current_user_quizes[list['quiz_id']] = db_query_single("SELECT * FROM user_has_quiz INNER JOIN user ON user_id=user.id WHERE quiz_id=%s", [list['quiz_id']])

    if user.get('is_admin'):
        user_has_quiz = db_query_rows("SELECT * FROM user_has_quiz INNER JOIN user ON user_id=user.id")
        users_quizes = {}
        for list in user_has_quiz:
            users_quizes[list['quiz_id']] = db_query_rows("SELECT * FROM user_has_quiz INNER JOIN user ON user_id=user.id WHERE quiz_id=%s", [list['quiz_id']])

        return render_template('quizes/home.html', quizes=quizes, users_quizes=users_quizes, current_user_quizes=current_user_quizes)
    else:
        return render_template('quizes/home.html', quizes=quizes, current_user_quizes=current_user_quizes)


@quizes.route('/user/answers', methods=['GET'])
def quiz():
    with MySqlCursor() as mc:
        myselect = mc.execute_select(
            '''
                SELECT username, answer, quiz.id, quiz.title
                FROM user
                INNER JOIN user_has_answer
                ON user.id = user_has_answer.user_id
                INNER JOIN answer
                ON answer.id = user_has_answer.answer_id
                INNER JOIN quiz
                ON answer.quiz_id = quiz.id;
            '''
        )
    # initialize an empty dictionary to store the answers
    quiz_answers = {}

    # loop through the user's answers and group them by quiz name
    for user_answer in myselect:
        username = user_answer[0]
        answer = user_answer[1]
        quiz_id = user_answer[2]
        quiz_name = user_answer[3]
        if quiz_name not in quiz_answers:
            quiz_answers[quiz_name] = {username: [answer]}
        elif username in quiz_answers[quiz_name]:
            quiz_answers[quiz_name][username].append(answer)
        elif username not in quiz_answers[quiz_name]:
            quiz_answers[quiz_name][username] = [answer]


    if request.method == 'GET':
        return render_template('admin_dashboard_quiz.html', quiz_answers=quiz_answers)

@quizes.route('/create', methods=['POST', 'GET'])
@admin_required
def create_quiz():
    form = QuizForm()
    if form.validate_on_submit():
        title = form.title.data
        active = form.active.data
        quiz_id = db_exec('''INSERT INTO quiz (title, active) VALUES (%s, %s);''', [title, active])
        flash(f'successfully created quiz {title}', 'success')
        return redirect(url_for('questions.create_question', quiz_id=quiz_id))
    return render_template('quizes/create.html', form=form)

@quizes.route('/update/<int:id>', methods=['POST', 'GET'])
def update_quiz(id):
    form = QuizForm()
    if form.validate_on_submit():
        if request.form.get('submit') == 'Update':
            title = form.title.data
            active = form.active.data
            comment = form.comment.data
            db_exec('''UPDATE quiz SET title=%s, active=%s, comment=%s WHERE id=%s''', [title, active, comment, id])
            flash(f'successfully updated quiz {title}', 'success')
        elif request.form.get('submit') == 'Cancel':
            flash(f'successfully cancelled', 'success')
        return redirect(url_for('home'))
    
    if request.method == 'GET':
        quiz = db_query_single("SELECT * FROM quiz WHERE id=%s", [id])
        form.title.data = quiz['title']
        form.active.data = quiz['active']
        form.comment.data = quiz['comment']

        return render_template('quizes/update.html', form=form)

@quizes.route('/<user_id>/quiz/<int:quiz_id>/approve/<int:approved>', methods=['POST', 'GET'])
@admin_required
def approve(user_id, approved, quiz_id):
    form = TextAreaForm()
    if form.validate_on_submit():
        comment = form.text.data
        db_exec('''UPDATE user_has_quiz SET approved=%s, comment=%s WHERE user_id=%s AND quiz_id=%s''', [approved, comment, user_id, quiz_id])
        flash(f'Successfully approved quiz {quiz_id}', category='success')
        return redirect(url_for('quizes.home'))
    return render_template('quizes/approve.html', form=form)

@quizes.route('/review/<int:id>', methods=['POST', 'GET'])
def review(id):
    quiz = db_query_single("SELECT * FROM quiz WHERE id=%s", [id])
    questions = db_query_rows('''SELECT * FROM question WHERE id IN (SELECT DISTINCT(answer_question_id) FROM user_has_answer WHERE answer_question_quiz_id=%s);''', [id])
    user_has_question = db_query_rows('''SELECT * FROM user_has_question WHERE question_quiz_id=%s;''', [id])
    # user_ids = [user['user_id'] for user in user_has_question]

    users_answers = {}
    for question in questions:
        users_answers[question['id']] = db_query_rows('''
        SELECT user_id, answer_id, answer_question_id as question_id, answer_question_quiz_id as quiz_id, essay, username, answer.answer, question.title, question.content, question.answer_type, question.category
        FROM user_has_answer 
        INNER JOIN user ON user_id=user.id 
        INNER JOIN answer ON answer_id=answer.id
        INNER JOIN question ON question_id=question.id
        WHERE answer_question_id=%s;''', [question['id']])
    
    return render_template('quizes/review.html', users_answers=users_answers, quiz=quiz)

@quizes.route('/read/<int:id>', methods=['POST', 'GET'])
def read_quiz(id):
    user_id=session.get('id')
    if request.method == 'POST':
        if request.form.get('type') != 'essay':
            answer_ids = request.form.getlist('answer')
            for answer_id in answer_ids:
                answer_id = int(answer_id)
                answer = db_query_single("SELECT * FROM answer WHERE id=%s", [answer_id])
                question_id = answer['question_id']
                db_exec('''INSERT INTO user_has_answer (user_id, answer_id, answer_question_id, answer_question_quiz_id) VALUES (%s, %s, %s, %s)''', [session.get('id'), answer_id, question_id, id])
                db_exec('''INSERT INTO user_has_question (user_id, question_id, question_quiz_id, is_answered) VALUES (%s, %s, %s, %s)''', [session.get('id'), question_id, id, 1])
                flash(f'succesfully inserted answer {answer_id} for question {question_id} for quiz {id}', 'success')
            if not answer_ids:
                flash('you must select at least one answer', 'danger')
        else:
            keys_values_ending_with_text = [value for key, value in request.form.items() if key.endswith('text')]
            keys_values_ending_with_id = [value for key, value in request.form.items() if key.endswith('id')]

            zipped_pairs = zip(keys_values_ending_with_id, keys_values_ending_with_text)

            for key, value in zipped_pairs:
                answer_id = key
                question_id = db_query_single("SELECT question_id FROM answer WHERE id=%s", [answer_id])['question_id']
                essay = value
                db_exec('''INSERT INTO user_has_answer (user_id, answer_id, answer_question_id, answer_question_quiz_id, essay) VALUES (%s, %s, %s, %s, %s)''', [session.get('id'), answer_id, question_id, id, essay])
                db_exec('''INSERT INTO user_has_question (user_id, question_id, question_quiz_id, is_answered) VALUES (%s, %s, %s, %s)''', [session.get('id'), question_id, id, 1])
                flash(f'succesfully inserted answer {answer_id} for question {question_id} for quiz {id}', 'success')

        return redirect(url_for('quizes.read_quiz', id=id))

    if request.method == 'GET':
        quiz = db_query_single("SELECT * FROM quiz WHERE id=%s", [id])
        quiz_completed = db_query_single("SELECT * FROM user_has_quiz WHERE user_id=%s AND quiz_id=%s", [session.get('id'), id])
        if quiz_completed:
            if quiz_completed.get( 'is_completed' ):
                flash(f'you have completed all questions from {quiz.get("title")}', 'success')
                return redirect(url_for('quizes.home'))
        questions = db_query_rows("SELECT * FROM question WHERE quiz_id=%s", [id])
        # questions_not_answered = db_query_rows("SELECT question.*, user_id, is_answered FROM `question` LEFT JOIN user_has_question as uhq ON id=uhq.question_id WHERE uhq.is_answered IS NULL AND quiz_id = %s", [id])
        # if not questions_not_answered:
        #     db_exec('''INSERT INTO user_has_quiz (user_id, quiz_id, is_completed) VALUES (%s, %s, %s)''', [session.get('id'), id, 1])
        #     flash('you have completed all questions', 'success')
        #     return redirect(url_for('quizes.home'))
        # if id not in [q['id'] for q in questions_not_answered]:
        #     return redirect(url_for('questions.read_question', id=questions_not_answered[0]['id'], quiz_id=id))
        # answers = db_query_rows("SELECT * FROM answer WHERE question_quiz_id=%s", [id])
        answers = {}
        forms = {}
        is_answered = {}
        for question in questions:

quiz_app/users/__init__.py
from flask import Blueprint, session, render_template, redirect, url_for, request, flash, g

users = Blueprint('users', __name__, url_prefix='/users')

from ..forms import *

from ..quiz_register import *
from ..admin_register import *
from ..answer_register import *
from ..user_register import *
from ..user_has_quiz import *
from ..user_has_answer import *
from ..mysql_cursor import *
from ..db import *
from ..utils import *

import werkzeug


# @users.after_request
# def after_request(response):
#     # Modify the response based on the data in g
#     user = g.user
#     response.headers['X-User'] = user

@users.route('/', methods=['POST', 'GET'])
@admin_required
def home():
    users = db_query_rows("SELECT * FROM user")
    return render_template('users/home.html', users=users)


@users.route('/profile')
@login_required
def profile():
    # Access the user from the g object
    user = g.user

    # If the user is not stored in g, retrieve the user based on the session
    if not user:
        user_id = session.get('id')
        if user_id:
            user = get_user_by_id(user_id)
            g.user = user

    if user:
        return f"Welcome, {user['username']}!"
    else:
        return 'Unauthorized'



@users.route('/register', methods=["GET", "POST"])
def register():
    check_logged_in()
    form = RegistrationForm()
    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        password_hash = werkzeug.security.generate_password_hash(form.password.data)
        first_name = form.first_name.data
        last_name = form.last_name.data
        is_admin = form.is_admin.data
        db_exec('''INSERT INTO user (username, email, password_hash, first_name, last_name, is_admin) 
        VALUES (%s, %s, %s, %s, %s, %s)''', 
        (username, email, password_hash, first_name, last_name, is_admin))
        flash(f'Successfully created admin {username}', category='success')
        return redirect(url_for('home'))
        
    return render_template('users/register.html', form=form)



@users.route('/logout', methods=["GET", "POST"])
@login_required
def logout():
    user = get_user()
    session.clear() # clear the rest
    if user.get('is_admin'):
        flash(f'logged out as admin {user.get("username")}', 'info')
    elif user.get('is_regular'):
        flash(f'logged out as user', 'info')
    elif user.get('is_anonymous'):
        flash(f'logged out as guest', 'info')
    return redirect(url_for('home'))


@users.route('/login/user/type', methods=['GET', 'POST'])
def login_user_type():
    form = UserTypeForm()
    if form.validate_on_submit():
        if form.usertype.data == 'admin':
            return redirect(url_for('users.login'))
        elif form.usertype.data == 'user':
            return redirect(url_for('users.login'))
        elif form.usertype.data == 'guest':
            session['id'] = db_exec('''INSERT INTO user (is_anonymous, is_regular, is_admin) VALUES (%s, %s, %s)''', (1,0,0))
            return redirect(url_for('home'))
        else:
            flash(f'Invalid user type { form.usertype.data}', category='error')
            return redirect(url_for('users.login_user_type'))
    else:
        return render_template('users/user_type.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if not session.get('id'):
        form = LoginForm()
        if form.validate_on_submit():
            username = form.username.data
            password = form.password.data
            user = db_query_single("SELECT * FROM user WHERE username=%s", [username])
            if user:
                if werkzeug.security.check_password_hash(user.get('password_hash'), password):
                    session['id'] = user.get('id')
                    if user.get('is_admin'):
                        flash(f'Successfully logged in as admin {username}', category='success')
                    else:
                        flash(f'Successfully logged in as user {username}', category='success')
                    return redirect(url_for('home'))
                else:
                    flash('Incorrect password', category='error')
                    return redirect(url_for('users.login'))
            else:
                flash(f'user does not exist {username}', category='error')
                return redirect(url_for('users.login'))
        return render_template('users/login.html', form=form)
    else:
        flash(f"Already logged in", category='success')
        return redirect(url_for('home'))



@users.route('/create', methods=['POST', 'GET'])
@admin_required
def create():
    form = QuizForm()
    if form.validate_on_submit():
        title = form.title.data
        active = form.active.data
        comment = form.comment.data
        conn = db_get_connection()
        cursor = conn.cursor()
        cursor.execute('''INSERT INTO quiz (title, active, comment) VALUES (%s, %s, %s);''', [title, active, comment])
        quiz_id = cursor.lastrowid
        conn.commit();cursor.close();conn.close()
        flash(f'successfully created quiz {title}', 'success')
        return redirect(url_for('questions.create_question', quiz_id=quiz_id))
    return render_template('quizes/create.html', form=form)

@users.route('/update/<int:id>', methods=['POST', 'GET'])
@admin_required
def update(id):
    form = QuizForm()
    if form.validate_on_submit():
        title = form.title.data
        active = form.active.data
        comment = form.comment.data
        db_exec('''UPDATE quiz SET title=%s, active=%s, comment=%s WHERE id=%s''', [title, active, comment, id])
        flash(f'successfully edited quiz{title}', 'success')
        return redirect(url_for('home'))
        
    if request.method == 'GET':
        quiz = db_query_single("SELECT * FROM quiz WHERE id=%s", [id])
        form.title.data = quiz['title']
        form.active.data = quiz['active']
        form.comment.data = quiz['comment']

        return render_template('quizes/update.html', form=form)

@users.route('/read/<int:id>', methods=['POST', 'GET'])
def read(id):
    if request.method == 'GET':
        user = db_query_single("SELECT * FROM user WHERE id=%s", [id])
        user_answers = db_query_rows("SELECT * FROM user_has_answer WHERE id=%s", [id])
        return render_template('users/read.html')


@users.route('/delete/<int:id>', methods=['POST', 'GET'])
@admin_required
def delete(id):
    # delete on cascade
    user = db_query_single("SELECT * FROM user WHERE id=%s", [session.get('id')])
    db_exec('''DELETE FROM user WHERE id=%s''', [id])
    flash(f'Successfully deleted user: {id}', 'success')
    return redirect(url_for('home'))

quiz_app/templates/about.html
{% extends "layout.html" %}
{% block title %}
About us
{% endblock %}
{% block content %}
<p>about page for blah blah blah</p>
{% endblock %}

quiz_app/templates/admin_dashboard.html
{% extends "layout.html" %}
{% block title %}
user dashboard
{% endblock %}
{% block content %}
    <div id="flash-messages">
        {% with messages = get_flashed_messages(with_categories=true) %}  
            {% if messages %}  
                {% for category, message in messages %}  
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}  
            {% endif %}  
        {% endwith %}  
    </div>
    <div class="container">
        <h1>Quiz Dashboard</h1>
        <hr>
        <div class="row">
            <div class="col-md-4">
                <a href="{{ url_for('admin_dashboard_quiz') }}" class="btn btn-primary btn-block mb-3">Browse Quizzes</a><br>
                <a href="{{ url_for('admin_dashboard_quiz_new') }}" class="btn btn-success btn-block mb-3">Create New Quiz</a><br>
                <a href="{{ url_for('admin_dashboard_users') }}" class="btn btn-dark btn-block mb-3">Browse Users</a>
            </div>
            <div class="col-md-8">
                <h2>Existing Quizzes</h2>
                {% for quiz in quizes %}
                    <div class="card mb-3" id="quiz-{{ loop.index0 }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ quiz[1] }}</h5>
                            <p class="card-text">{{ quiz[2] }}</p>
                            <a href="{{ url_for('admin_dashboard_quiz_edit', id=quiz[0]) }}" class="btn btn-primary">Edit Quiz</a>
                            <a href="{{ url_for('admin_dashboard_quiz_delete', quiz_id=quiz[0]) }}" class="btn btn-danger">Delete Quiz</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

quiz_app/templates/admin_dashboard_quiz.html
{% extends "layout.html" %}
{% block title %}
admin quiz
{% endblock %}
{% block content %}
    <h1>Quiz Results</h1>
    <div id="flash-messages">
        {% with messages = get_flashed_messages(with_categories=true) %}  
            {% if messages %}  
                {% for category, message in messages %}  
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}  
            {% endif %}  
        {% endwith %}  
    </div>
    {% for quiz_name, usernames in quiz_answers.items() %}
        <div class="quiz-container" id="quiz-{{ loop.index0 }}">
            <h2 class="quiz-title">{{quiz_name}}</h2>
            <ul class="user-list">
            {% for username, answers in usernames.items() %}
                <div class="user-container">
                    <li><h3 class="user-title">{{username}}</h3></li>
                    <ul class="answer-list">
                        {% for answer in answers %}
                            <li class="answer-item">{{answer}}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
            </ul>
        </div>
    {% endfor %}
{% endblock %}

quiz_app/templates/admin_dashboard_quiz_edit.html
{% extends "layout.html" %}
{% block title %}
New quiz 
{% endblock %}
{% block content %}
    <div id="flash-messages">
        {% with messages = get_flashed_messages(with_categories=true) %}  
            {% if messages %}  
                {% for category, message in messages %}  
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}  
            {% endif %}  
        {% endwith %}  
    </div>
    <form method="POST" action="">
        {{ form.csrf_token }}
        <fieldset class="form-group">
            <legend>Quiz maker</legend>
                <div>
                    {{ form.title.label }} {{ form.title}} <br>
                    {% for error in form.title.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
                <div>
                    {{ form.question.label }} {{ form.question }} <br>
                    {% for error in form.question.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
                    
                <div id="answers">
                    {{form.answer1.label}} {{form.answer1}}
                    {{form.correct1.label}} {{form.correct1}}
                    <br>
                    {{form.answer2.label}} {{form.answer2}}
                    {{form.correct2.label}} {{form.correct2}}
                    <br>
                    {{form.answer3.label}} {{form.answer3}}
                    {{form.correct3.label}} {{form.correct3}}
                    <br>
                    {{form.answer4.label}} {{form.answer4}}
                    {{form.correct4.label}} {{form.correct4}}
                    <br>
                </div>

                <div>
                    {{ form.active.label }} {{ form.active }} <br>
                    {% for error in form.active.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </div>

                <div>
                    {{ form.category.label }} {{ form.category}} <br>
                    {% for error in form.category.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
                {{ form.submit(class="btn btn-primary", value='Edit')}}
        </fieldset>
    </form>
{% endblock %}

quiz_app/templates/admin_dashboard_users.html
{% extends "layout.html" %}
{% block title %}
admin quiz
{% endblock %}
{% block content %}
    <div id="flash-messages">
        {% with messages = get_flashed_messages(with_categories=true) %}  
            {% if messages %}  
                {% for category, message in messages %}  
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}  
            {% endif %}  
        {% endwith %}  
    </div>
    {% for user in users %}
        <div class="container my-4" id="quiz-{{ loop.index0 }}">
            <ul class="list-group">
                <li class="list-group-item bg-dark text-white"><strong>User ID:</strong> {{ user[0] }}</li>
                <li class="list-group-item bg-light"><strong>Username:</strong> {{ user[1] }}</li>
            </ul>
        </div>
    {% endfor %}


{% endblock %}

quiz_app/templates/admin_register.html
{% extends "layout.html" %}
{% block title %}
admin register
{% endblock %}
{% block content %}
    <form method="POST" action="" class="register-form">
        {{ form.csrf_token() }}
        <fieldset class="form-group">
            <legend class="form-legend">Admin Register</legend>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="first_name" class="form-label">First Name</label>
                    {{ form.first_name(class="form-control", id="first_name", placeholder="Enter your first name") }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="last_name" class="form-label">Last Name</label>
                    {{ form.last_name(class="form-control", id="last_name", placeholder="Enter your last name") }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="username" class="form-label">Username</label>
                    {{ form.username(class="form-control", id="username", placeholder="Enter your username") }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="password" class="form-label">Password</label>
                    {{ form.password(class="form-control", id="password", placeholder="Enter your password") }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="confirm_password" class="form-label">Confirm Password</label>
                    {{ form.confirm_password(class="form-control", id="confirm_password", placeholder="Confirm your password") }}
                </div>
            </div>
            {% for field, errors in form.errors.items() %}
                <div class="alert alert-danger">{{ ', '.join(errors) }}</div>
            {% endfor %}
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.submit(class="btn btn-primary btn-block", value="Register") }}
                </div>
            </div>
        </fieldset>
    </form>

{% endblock %}

quiz_app/templates/contact.html
{% extends "layout.html" %}
{% block title %}
Contact us
{% endblock %}
{% block content %}
<form action="{{ url_for('submit_form') }}" method="POST">
    <label for="fname">First name:</label>
        <input type="text" id="fname" name="fname"><br><br>

        <label for="lname">Last name:</label>
        <input type="text" id="lname" name="lname"><br><br>

        <label for="em">email:</label>
        <input type="email" id="em" name="em"><br><br>

        <label for="birthday">birthday:</label>
        <input type="date" id="birthday" name="birthday"><br><br>

        <label for="webaddr">web adress:</label>
        <input type="url" id="webaddr" name="webaddr"><br><br>

        <label for="meldingboks">melding boks:</label>
        <input type="textarea" id="meldingboks" name="meldingboks"><br><br>

        <label for="pet-select">Choose a pet:</label>
        <select name="pets" id="pet-select">
            <option value="">--Please choose an option--</option>
            <option value="dog">Dog</option>
            <option value="cat">Cat</option>
            <option value="hamster">Hamster</option>
            <option value="parrot">Parrot</option>
            <option value="spider">Spider</option>
            <option value="goldfish">Goldfish</option>
        </select>

        <button type="submit">Submit</button>
    </form>

{% endblock %}

quiz_app/templates/flash_messages.html
    <div id="flash-messages" class="m-3">
        {% with messages = get_flashed_messages(with_categories=true) %}  
            {% if messages %}  
                {% for category, message in messages %}  
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}  
            {% endif %}  
        {% endwith %}  
    </div>

quiz_app/templates/hello_there.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Hello, Flask</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='site.css')}}" />

    </head>
    <body>
        {%if name %}
            <span class="message">Hello there, {{ name }}!</span> It's {{ date.strftime("%A, %d %B, %Y at %X") }}.
        {% else %}
            <span class="message">What's your name? Provide it after /hello/ in the URL.</span>
        {% endif %}
    </body>
</html>

quiz_app/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
        <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script> -->
        <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='site.css')}}" />
    </head>

    <body>
        {% block nav %}
            <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="{{ url_for('home') }}">QuizMaster 2023</a>
                    </div>
                    <ul class="navbar-nav mr-auto-lg mb-2 mb-lg-0">
                        <li class="navbar-item"><a class="nav-link active " href="{{ url_for('home') }}"><span class="fas fa-home"></span> Home</a></li>
                        <li class="navbar-item"><a class="nav-link active" href="{{ url_for('quizes.home') }}"><span class="fas fa-plus"></span> Quizes</a></li>
                        {% if is_admin %}
                            <li class="navbar-item"><a class="nav-link active " href="{{ url_for('quizes.create_quiz') }}"><span class=""></span> Create quiz</a></li>
                            <li class="navbar-item"><a class="nav-link active " href="{{ url_for('users.home') }}"><span class=""></span>Users</a></li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                        {% if not session.get('id') %}
                            <li class="navbar-item"><a class="nav-link active" href="{{ url_for('users.register') }}"><span class="fas fa-user-plus"></span> Sign Up </a></li>
                            <li class="navbar-item"><a class="nav-link active" href="{{ url_for('users.login') }}"><span class="fas fa-sign-in-alt"></span> Login </a></li>
                        {% else %}
                            <li class="navbar-item"><a class="nav-link active" href="{{ url_for('users.logout') }}"><span class="fas fa-sign-out-alt"></span> Logout </a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        {% endblock nav %}

        <main class="container">
            {% block content %}
            {% endblock %}
            <hr/>
        </main>
        <footer>
            <p>&copy; 2023</p>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>