quiz_app/quizes/__init__.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session

from quiz_app.mysql_cursor import MySqlCursor
from quiz_app.forms import *

from ..quiz_register import *
from ..admin_register import *
from ..answer_register import *
from ..user_register import *
from ..user_has_quiz import *
from ..user_has_answer import *
from ..mysql_cursor import *
from ..db import *
from ..utils import *

import random

quizes = Blueprint('quizes', __name__, url_prefix='/quizes')


@quizes.route('/index')
@quizes.route('/home')
@quizes.route('/')
def home():
    user = db_query_single("SELECT * FROM user WHERE id=%s", [session.get('id')])
    quizes = db_query_rows("SELECT * FROM quiz")

    current_user_has_quiz = db_query_rows("SELECT * FROM user_has_quiz INNER JOIN user ON user_id=user.id WHERE user_id=%s", [session.get('id')])
    current_user_quizes = {}
    if current_user_has_quiz:
        for list in current_user_has_quiz:
            current_user_quizes[list['quiz_id']] = db_query_single("SELECT * FROM user_has_quiz INNER JOIN user ON user_id=user.id WHERE quiz_id=%s", [list['quiz_id']])

    if user.get('is_admin'):
        user_has_quiz = db_query_rows("SELECT * FROM user_has_quiz INNER JOIN user ON user_id=user.id")
        users_quizes = {}
        for list in user_has_quiz:
            users_quizes[list['quiz_id']] = db_query_rows("SELECT * FROM user_has_quiz INNER JOIN user ON user_id=user.id WHERE quiz_id=%s", [list['quiz_id']])

        return render_template('quizes/home.html', quizes=quizes, users_quizes=users_quizes, current_user_quizes=current_user_quizes)
    else:
        return render_template('quizes/home.html', quizes=quizes, current_user_quizes=current_user_quizes)


@quizes.route('/user/answers', methods=['GET'])
def quiz():
    with MySqlCursor() as mc:
        myselect = mc.execute_select(
            '''
                SELECT username, answer, quiz.id, quiz.title
                FROM user
                INNER JOIN user_has_answer
                ON user.id = user_has_answer.user_id
                INNER JOIN answer
                ON answer.id = user_has_answer.answer_id
                INNER JOIN quiz
                ON answer.quiz_id = quiz.id;
            '''
        )
    # initialize an empty dictionary to store the answers
    quiz_answers = {}

    # loop through the user's answers and group them by quiz name
    for user_answer in myselect:
        username = user_answer[0]
        answer = user_answer[1]
        quiz_id = user_answer[2]
        quiz_name = user_answer[3]
        if quiz_name not in quiz_answers:
            quiz_answers[quiz_name] = {username: [answer]}
        elif username in quiz_answers[quiz_name]:
            quiz_answers[quiz_name][username].append(answer)
        elif username not in quiz_answers[quiz_name]:
            quiz_answers[quiz_name][username] = [answer]


    if request.method == 'GET':
        return render_template('admin_dashboard_quiz.html', quiz_answers=quiz_answers)

@quizes.route('/create', methods=['POST', 'GET'])
@admin_required
def create_quiz():
    form = QuizForm()
    if form.validate_on_submit():
        title = form.title.data
        active = form.active.data
        quiz_id = db_exec('''INSERT INTO quiz (title, active) VALUES (%s, %s);''', [title, active])
        flash(f'successfully created quiz {title}', 'success')
        return redirect(url_for('questions.create_question', quiz_id=quiz_id))
    return render_template('quizes/create.html', form=form)

@quizes.route('/update/<int:id>', methods=['POST', 'GET'])
def update_quiz(id):
    form = QuizForm()
    if form.validate_on_submit():
        if request.form.get('submit') == 'Update':
            title = form.title.data
            active = form.active.data
            comment = form.comment.data
            db_exec('''UPDATE quiz SET title=%s, active=%s, comment=%s WHERE id=%s''', [title, active, comment, id])
            flash(f'successfully updated quiz {title}', 'success')
        elif request.form.get('submit') == 'Cancel':
            flash(f'successfully cancelled', 'success')
        return redirect(url_for('home'))
    
    if request.method == 'GET':
        quiz = db_query_single("SELECT * FROM quiz WHERE id=%s", [id])
        form.title.data = quiz['title']
        form.active.data = quiz['active']
        form.comment.data = quiz['comment']

        return render_template('quizes/update.html', form=form)

@quizes.route('/<user_id>/quiz/<int:quiz_id>/approve/<int:approved>', methods=['POST', 'GET'])
@admin_required
def approve(user_id, approved, quiz_id):
    form = TextAreaForm()
    if form.validate_on_submit():
        comment = form.text.data
        db_exec('''UPDATE user_has_quiz SET approved=%s, comment=%s WHERE user_id=%s AND quiz_id=%s''', [approved, comment, user_id, quiz_id])
        flash(f'Successfully approved quiz {quiz_id}', category='success')
        return redirect(url_for('quizes.home'))
    return render_template('quizes/approve.html', form=form)

@quizes.route('/review/<int:id>', methods=['POST', 'GET'])
def review(id):
    quiz = db_query_single("SELECT * FROM quiz WHERE id=%s", [id])
    questions = db_query_rows('''SELECT * FROM question WHERE id IN (SELECT DISTINCT(answer_question_id) FROM user_has_answer WHERE answer_question_quiz_id=%s);''', [id])
    user_has_question = db_query_rows('''SELECT * FROM user_has_question WHERE question_quiz_id=%s;''', [id])
    # user_ids = [user['user_id'] for user in user_has_question]

    users_answers = {}
    for question in questions:
        users_answers[question['id']] = db_query_rows('''
        SELECT user_id, answer_id, answer_question_id as question_id, answer_question_quiz_id as quiz_id, essay, username, answer.answer, question.title, question.content, question.answer_type, question.category
        FROM user_has_answer 
        INNER JOIN user ON user_id=user.id 
        INNER JOIN answer ON answer_id=answer.id
        INNER JOIN question ON question_id=question.id
        WHERE answer_question_id=%s;''', [question['id']])
    
    return render_template('quizes/review.html', users_answers=users_answers, quiz=quiz)

@quizes.route('/read/<int:id>', methods=['POST', 'GET'])
def read_quiz(id):
    user_id=session.get('id')
    if request.method == 'POST':
        if request.form.get('type') != 'essay':
            answer_ids = request.form.getlist('answer')
            for answer_id in answer_ids:
                answer_id = int(answer_id)
                answer = db_query_single("SELECT * FROM answer WHERE id=%s", [answer_id])
                question_id = answer['question_id']
                db_exec('''INSERT INTO user_has_answer (user_id, answer_id, answer_question_id, answer_question_quiz_id) VALUES (%s, %s, %s, %s)''', [session.get('id'), answer_id, question_id, id])
                db_exec('''INSERT INTO user_has_question (user_id, question_id, question_quiz_id, is_answered) VALUES (%s, %s, %s, %s)''', [session.get('id'), question_id, id, 1])
                flash(f'succesfully inserted answer {answer_id} for question {question_id} for quiz {id}', 'success')
            if not answer_ids:
                flash('you must select at least one answer', 'danger')
        else:
            keys_values_ending_with_text = [value for key, value in request.form.items() if key.endswith('text')]
            keys_values_ending_with_id = [value for key, value in request.form.items() if key.endswith('id')]

            zipped_pairs = zip(keys_values_ending_with_id, keys_values_ending_with_text)

            for key, value in zipped_pairs:
                answer_id = key
                question_id = db_query_single("SELECT question_id FROM answer WHERE id=%s", [answer_id])['question_id']
                essay = value
                db_exec('''INSERT INTO user_has_answer (user_id, answer_id, answer_question_id, answer_question_quiz_id, essay) VALUES (%s, %s, %s, %s, %s)''', [session.get('id'), answer_id, question_id, id, essay])
                db_exec('''INSERT INTO user_has_question (user_id, question_id, question_quiz_id, is_answered) VALUES (%s, %s, %s, %s)''', [session.get('id'), question_id, id, 1])
                flash(f'succesfully inserted answer {answer_id} for question {question_id} for quiz {id}', 'success')

        return redirect(url_for('quizes.read_quiz', id=id))

    if request.method == 'GET':
        quiz = db_query_single("SELECT * FROM quiz WHERE id=%s", [id])
        quiz_completed = db_query_single("SELECT * FROM user_has_quiz WHERE user_id=%s AND quiz_id=%s", [session.get('id'), id])
        if quiz_completed:
            if quiz_completed.get( 'is_completed' ):
                flash(f'you have completed all questions from {quiz.get("title")}', 'success')
                return redirect(url_for('quizes.home'))
        questions = db_query_rows("SELECT * FROM question WHERE quiz_id=%s", [id])
        # questions_not_answered = db_query_rows("SELECT question.*, user_id, is_answered FROM `question` LEFT JOIN user_has_question as uhq ON id=uhq.question_id WHERE uhq.is_answered IS NULL AND quiz_id = %s", [id])
        # if not questions_not_answered:
        #     db_exec('''INSERT INTO user_has_quiz (user_id, quiz_id, is_completed) VALUES (%s, %s, %s)''', [session.get('id'), id, 1])
        #     flash('you have completed all questions', 'success')
        #     return redirect(url_for('quizes.home'))
        # if id not in [q['id'] for q in questions_not_answered]:
        #     return redirect(url_for('questions.read_question', id=questions_not_answered[0]['id'], quiz_id=id))
        # answers = db_query_rows("SELECT * FROM answer WHERE question_quiz_id=%s", [id])
        answers = {}
        forms = {}
        is_answered = {}
        for question in questions:

quiz_app/templates/quizes/approve.html
{% extends "layout.html" %}
{% block title %}
question approve
{% endblock %}
{% block content %}
{% include "flash_messages.html" %}
    <h1>quiz approve</h1>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div class="card m-3">
            <div class="card-body">
                <h2>Add a comment</h2>
                {{ form.id() }}
                {{ form.text(class="form-control mb-3") }}
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </div>
    </form>
{% endblock %}

quiz_app/templates/quizes/create.html
{% extends "layout.html" %}
{% block title %}
create quiz 
{% endblock %}
{% block content %}
    <div id="flash-messages">
        {% with messages = get_flashed_messages(with_categories=true) %}  
            {% if messages %}  
                {% for category, message in messages %}  
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}  
            {% endif %}  
        {% endwith %}  
    </div>
    <form method="POST" action="" id="quiz_form">
    {{ form.csrf_token }}
    <fieldset class="form-group">
        <legend>Create quiz</legend>
        <div class="mb-3">
            {{ form.title.label(class="form-label") }} {{ form.title(class="form-control") }} 
        </div>
        <div class="mb-3 form-check">
            {{ form.active(class="form-check-input") }} {{ form.active.label(class="form-check-label") }} 
        </div>
        {{ form.submit(class="btn btn-primary")}}
    </fieldset>
    </form>


    {#
    {% if question_form %}
    <form method="POST" action="">
    {{ question_form.csrf_token }}
    <fieldset class="form-group">
        <legend>Create question</legend>
        <div class="mb-3">
            {{ question_form.title.label(class="form-label") }} {{ question_form.title(class="form-control") }} 
        </div>
        <div class="mb-3">
            {{ question_form.content.label(class="form-label") }} 
            {{ question_form.content(class="form-control") }} 
        </div>
        <div class="mb-3">
            {{ question_form.answer_type.label(class="form-label") }} 
            {{ question_form.answer_type(class="form-control") }} 
        </div>
        <div class="mb-3">
            {{ question_form.category.label(class="form-label") }} 
            {{ question_form.category(class="form-control") }} 
        </div>
        {{ question_form.submit(class="btn btn-primary")}}
    </fieldset>
    </form>
    {% endif %}
        #}

    <!-- <button type="submit" class="btn btn-primary" form="quiz_form">Submit Quiz</button> -->


{% endblock %}
{% block script %}
    <script>
         function createForm() {
            // Create a new form element
            var form = document.createElement('form');
            form.id = 'dynamicForm';

            // Load the content from an external HTML file
            var xhr = new XMLHttpRequest();
            xhr.open('GET', 'questions/create.html', true);
            xhr.onreadystatechange = function() {
                if (xhr.readyState === 4 && xhr.status === 200) {
                form.innerHTML = xhr.responseText;

                // Append the form to a container or the document body
                document.getElementById('formContainer').appendChild(form);
                }
            };
            xhr.send();
        }
    </script>
{% endblock %}

quiz_app/templates/quizes/delete.html
{% extends "layout.html" %}
{% block title %}
delete quiz 
{% endblock %}
{% block content %}
    <div id="flash-messages">
        {% with messages = get_flashed_messages(with_categories=true) %}  
            {% if messages %}  
                {% for category, message in messages %}  
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}  
            {% endif %}  
        {% endwith %}  
    </div>
    <form method="POST" action="">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <fieldset class="form-group">
        <legend>delete quiz</legend>
        <div class="mb-3">
            <h1>Are you sure you want to delete this quiz</h1>
            <input type="submit" class="btn btn-danger" value="delete" name="submit">
            <input type="submit" class="btn btn-primary" value="cancel" name="submit">
        </div>
    </fieldset>
    </form>

{% endblock %}

quiz_app/templates/quizes/home.html
{% extends "layout.html" %}
{% block title %}
Quizes home
{% endblock %}
{% block content %}
    {% include "flash_messages.html" %}

    <h1>Quizes</h1>
    {% if is_admin %}
    <div class="card m-3" id="create-quiz">
        <a href="{{ url_for('quizes.create_quiz') }}" class="btn btn-primary">Create quiz</a>
    </div>
    {% endif %}

    {% for quiz in quizes if quiz.active %}
        <div class="card m-3">
            <div class="card-body">
                <h5 class="card-title">{{ quiz.title }}</h5>
                {% if current_user_quizes %}
                    {% if current_user_quizes.get(quiz.id).is_completed %}
                        <span class="badge bg-success">completed</span>
                        {% if current_user_quizes.get(quiz.id) %}
                            <div class="alert alert-success">
                                {{ current_user_quizes.get(quiz.id).comment }}
                            </div>
                        {% endif %}
                    {% else %}
                        <span class="badge bg-warning">not completed</span>
                    {% endif %} 
                {% else %}
                    <span class="badge bg-warning">not completed</span>
                {% endif %}
                {% if is_admin %}
                    <div class="container">
                        <h6>Users in this quiz</h6>
                        {% if users_quizes.get(quiz.id) %}
                            {% for uq in users_quizes.get(quiz.id) %}
                                <div class="row">
                                    <div class="col">user id: {{ uq.user_id }}</div>
                                    <div class="col">username: {{ uq.username }}</div>
                                    <div class="col">quiz id: {{ uq.quiz_id }}</div>
                                    <div class="col">completed: {{ uq.is_completed }}</div>
                                    <div class="col">approved: {{ uq.approved }}</div>
                                    <div class="col"><a href="{{ url_for('quizes.approve', user_id=uq.user_id, quiz_id=quiz.id, approved=1) }}" class="btn btn-success">Approve</a></div>
                                    <div class="col"><a href="{{ url_for('quizes.approve', user_id=uq.user_id, quiz_id=quiz.id, approved=0) }}" class="btn btn-danger">Reject</a></div>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                {% endif %}
                    
                <div class="card-footer">

                    <a href="{{ url_for('quizes.read_quiz', id=quiz.id) }}" class="btn btn-primary col">Read</a>
                    {% if is_admin %}
                        <a href="{{ url_for('questions.create_question', quiz_id=quiz.id) }}" class="btn btn-primary">Add question</a>
                        <a href="{{ url_for('quizes.update_quiz', id=quiz.id) }}" class="btn btn-primary">Update</a>
                        <a href="{{ url_for('quizes.review', id=quiz.id) }}" class="btn btn-primary">Review</a> 
                        <a href="{{ url_for('quizes.delete_quiz', id=quiz.id) }}" class="btn btn-danger">Delete</a>
                        {#
                            #}
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

quiz_app/templates/quizes/read.html
{% extends "layout.html" %}
{% block title %}
read quiz
{% endblock %}
{% block content %}
{% include 'flash_messages.html' %}
    {% if quiz and quiz.active %}
    <div class="quiz">
        <h1>{{ quiz['title'] }}</h1>
        {% if is_admin %}
            <a href="{{ url_for('quizes.update_quiz', id=quiz['id']) }}" class="btn btn-primary">update quiz</a>
            <a href="{{ url_for('questions.create_question', quiz_id=quiz['id']) }}" class="btn btn-primary">create question</a>
            <a href="{{ url_for('quizes.review', id=quiz['id']) }}" class="btn btn-primary">review quiz</a>
            <a href="{{ url_for('quizes.delete_quiz', id=quiz['id']) }}" class="btn btn-danger">delete quiz</a>
        {% endif %}
        {% if questions %}
            <div class="container">
                {% for question in questions if not is_answered.get(question['id'])%}
                    {% set question_index = loop.index %}
                    <div class="card m-3">
                        <div class="card-body">
                            <h2>{{ question['content'] }}</h2>
                            {% if is_admin %}
                                <p>{{ question['answer_type'] }}</p>
                            {% endif %}
                            {% if answers[question['id']] %}
                                <form action="" method="post">
                                    {{ forms[question['id']].csrf_token }}
                                    {% if question['answer_type'] == 'single' %}
                                        <input type="hidden" name="type" value="single">
                                        {% for choice in forms[question['id']].answer %}
                                            <div class="form-check">
                                                {{ choice(class="form-check-input" , id="answer-" + loop.index|string + "-" + question_index|string) }}
                                                {{ choice.label(class="form-check-label", for="answer-" + loop.index|string + "-" + question_index|string) }}
                                            </div>
                                        {% endfor %}
                                    {% elif question['answer_type'] == 'multiple' %}
                                        <input type="hidden" name="type" value="multiple">
                                        {% for choice in forms[question['id']].answer %}
                                            <div class="form-check">
                                                {{ choice(class="form-check-input" , id="answer-" + loop.index|string + "-" + question_index|string) }}
                                                {{ choice.label(class="form-check-label", for="answer-" + loop.index|string + "-" + question_index|string) }}
                                            </div>
                                        {% endfor %}
                                        {#
                                            {{ forms[question['id']].answer(class="form-check", id="answer-" + question_index|string) }}
                                        {% for answer in answers[question['id']] %}
                                            <div class="form-check">
                                                <input type="hidden" name="answer_id" value="{{ answer['id'] }}">
                                                <label for="answer-{{ loop.index }}-{{ question_index }}" class="form-check-label" for="answer-{{ loop.index-question_index }}">{{ answer['answer'] }}</label>
                                                {{ forms[question['id']].answer(class="form-check-input", id="answer-" + loop.index|string + "-" + question_index|string) }} 
                                            </div>
                                        {% endfor %}
                                            #}
                                    {% elif question['answer_type'] == 'essay' %}
                                        <input type="hidden" name="type" value="essay">
                                        {% for text_box in forms[question['id']].answer.entries %}
                                            <div class="m-3">
                                                {{ text_box.form.id() }}
                                                {{ text_box.form.text(class="form-control mb-3") }}
                                            </div>
                                        {% endfor %}
                                                {#
                                                    #}
                                    {% endif %}
                                    {{ forms[question['id']].submit(class="btn btn-primary m-3", id="submit-" + question_index|string) }}
                                </form>
                            {% endif %}
                            <a href="{{ url_for('questions.read_question', id=question['id']) }}" class="btn btn-primary mr-2" >read question</a>
                            {% if is_admin %}
                                <a href="{{ url_for('questions.update_question', id=question['id']) }}" class="btn btn-primary mr-2">update question</a>
                                <a href="{{ url_for('answers.create_answer', quiz_id=quiz['id'], question_id=question['id']) }}" class="btn btn-primary mr-2">add answer</a>
                                <a href="{{ url_for('questions.delete_question', id=question['id']) }}" class="btn btn-danger mr-2">delete question</a>
                            {% endif %}

                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    {% elif quizes %}
        {% for question in questions %}
            <div class="question-read">
                <h1>{{ question.title }}</h1>
                <p>{{ question.content }}</p>
                <p>{{ question.answer_type }}</p>
                <p>{{ question.category }}</p>
                <a href="{{ url_for('questions.delete', question_id=question['id']) }}">delete</a>
                <a href="{{ url_for('questions.update', question_id=question['id']) }}">update</a>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

quiz_app/templates/quizes/review.html
{% extends "layout.html" %}
{% block title %}
quiz review
{% endblock %}
{% block content %}
    {% include "flash_messages.html" %}
    <h1>{{ quiz.title }} review</h1>
    <h1>quiz id: {{ quiz.id }}</h1>

    {% for question_id, answers in users_answers.items() %}
        <div class="card m-3">
            <div class="card-body">
                <h2>{{ users_answers[question_id][0].title }} id: {{ question_id }}</h2>
                <h3>{{ users_answers[question_id][0].content }}</h3>
                {% for answer in answers %}
                    <div class="row row-black">
                        <div class="col">user id: {{ answer.user_id }}</div>
                        <div class="col">username: {{ answer.username }}</div>
                        {% if answer.answer_type == 'essay'%}
                            <div class="col">answer: {{ answer.essay }}</div>
                        {% else %}
                        <div class="col">answer: {{ answer.answer }}</div>
                        {% endif %}
                        <div class="col">answer type: {{ answer.answer_type }}</div>
                        <div class="col">answer id: {{ answer.answer_id }}</div>
                        <div class="col"><a class='btn btn-success'href="{{ url_for('questions.approve', user_id=answer.user_id, question_id=question_id, answer_id=answer.answer_id, quiz_id=quiz.id, approved=1) }}">approve</a></div>
                        <div class="col"><a class='btn btn-danger'href="{{ url_for('questions.approve', user_id=answer.user_id, question_id=question_id, answer_id=answer.answer_id, quiz_id=quiz.id, approved=0) }}">reject</a></div>
                        {#
                            #}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}

    {#
    {% for question in questions %}
        <div class="card m-3">
            <div class="card-body">
                <h2>{{ question.title }}</h2>
                <h3>{{ question.content }}</h3>
                {% for user_answer in users_answers %}
                    {% if user_answer.answer_question_id == question.id %}
                        <p>{{ user_answer }}</p>
                    {% endif %}
                {% endfor %}
            </div>
        </div>

    {% endfor %}
        #}


{% endblock %}

quiz_app/templates/quizes/update.html
{% extends "layout.html" %}
{% block title %}
Quizes update
{% endblock %}
{% block content %}
    <div id="flash-messages">
        {% with messages = get_flashed_messages(with_categories=true) %}  
            {% if messages %}  
                {% for category, message in messages %}  
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}  
            {% endif %}  
        {% endwith %}  
    </div>
    <form method="POST" action="" id="quiz_form">
    {{ form.csrf_token }}
    <fieldset class="form-group">
        <legend>Update quiz</legend>
        <div class="mb-3">
            {{ form.title.label(class="form-label") }} {{ form.title(class="form-control") }} 
        </div>
        <div class="mb-3 form-check">
            {{ form.active(class="form-check-input") }} {{ form.active.label(class="form-check-label") }} 
        </div>
        <div class="mb-3">
            {{ form.comment.label(class="form-label") }}
            {{ form.comment(class="form-control") }} 
        </div>
        <!-- <div id="formContainer">
            <button class="btn btn-secondary" onclick="createForm()">Add Question</button>
        </div> -->

        {#
        <div class="mb-3">
            <button type="submit" class="btn btn-secondary" formaction="{{ url_for('quizes.create_quiz', action='add') }}">Add question</button>
        </div>
            #}
        {{ form.submit(class="btn btn-primary", value="Update")}}
        {{ form.submit(class="btn btn-secondary", value="Cancel")}}
    </fieldset>
    </form>
{% endblock %}